[Interface]
# Key for server-primary
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = REDACTED
Address = 10.2.0.2/32
Table = off
PostUp = /home/matt/dotfiles/scripts/server/wg0-up-extra.sh

[Peer]
# CA#160 — replace PublicKey and Endpoint when swapping this profile's server
PublicKey = REDACTED
AllowedIPs = 0.0.0.0/0
Endpoint = 176.113.74.82:51820
PersistentKeepalive = 25
