services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /mnt/data:/srv
      - /mnt/data/filebrowser/database:/database
      - /mnt/data/filebrowser/config:/config
    ports:
      - "127.0.0.1:8081:80"
