#!/bin/sh
buf=$(cat)
encoded=$(printf '%s' "$buf" | base64 | tr -d '\n')
if [ -n "$TMUX" ]; then
  printf '\033Ptmux;\033\033]52;c;'"$encoded"'\a\033\\' > /dev/tty
else
  printf '\033]52;c;%s\a' "$encoded" > /dev/tty
fi
