[text]
appendEmptyLine=true
autoBracket=false
autoReplace=false
autoSave=false
autoSaveInterval=1
darkBgColorValue=15
darkColorScheme=true
dateFormat=
dictionaryPath=
executeCommand=
executeScripts=false
font="JetBrainsMono Nerd Font,14,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
inertialScrolling=false
lightBgColorValue=255
lineNumbers=false
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
openRecentFiles=0
pastePaths=true
recentFiles=
recentFilesNumber=10
recentOpened=false
removeTrailingSpaces=false
saveLastFilesList=false
saveUnmodified=false
scrollJumpWorkaround=false
selectionHighlighting=false
showEndings=false
showWhiteSpace=false
skipNonText=true
spellCheckFromStart=false
textMargin=false
textTabSize=4
thickCursor=false
vLineDistance=-80

[window]
closeWithLastTab=false
disableMenubarAccel=false
fullscreen=false
hideSearchbar=false
hideSingleTab=false
iconless=false
max=true
menubarTitle=false
nativeDialog=true
noMenubar=false
noToolbar=false
openInWindows=false
position=none
prefSize=@Size(420 530)
sharedSearchHistory=false
showCursorPos=false
showLangSelector=false
showStatusbar=false
sidePaneMode=false
size=@Size(1362 721)
splitterPos=150
startSize=@Size(700 500)
sysIcon=true
sysIcons=false
tabPosition=0
tabWrapAround=false
